on:
  push:
    branches:
      - '*'
  pull_request:


name: GoZilla CI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        go: ['1.14']
    name: GoZilla
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.0.3
        with:
          go-version: ${{ matrix.go }}
      - name: Setup env for GO
        #  this is only used until the setup-go action is updated
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - name: Setup golint
        run: |
          go env
          go install golang.org/x/lint/golint
      - name: Building
        run: make all
      - name: Running
        run: |
          ./bin/gozilla bug --id 1839234
