name: Releasing GoZilla

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gozilla
            asset_name: gozilla-linux-amd64
          - os: windows-latest
            artifact_name: gozilla.exe
            asset_name: gozilla-windows-amd64
          - os: macos-latest
            artifact_name: gozilla
            asset_name: gozilla-macos-amd64

    steps:
    - name: Setup go
      uses: actions/setup-go@v2.0.3
      with:
        go-version: ${{ matrix.go }}
    - name: Setup env for GO
      #  this is only used until the setup-go action is updated
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
    - name: Setup golint
      run: |
        go env
        go install golang.org/x/lint/golint
    - name: Building
      run: make all
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file:  ./bin/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}